services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cache-api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - cache-network

  redis:
    image: redis:7-alpine
    container_name: cache-redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - cache-network

networks:
  cache-network:
    driver: bridge

volumes:
  redis_data:
