version: '3.8'

services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - sqlite_data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///data/test.db
    restart: unless-stopped

volumes:
  sqlite_data:
    name: fastapi_sqlite_data
