name: Job Summary Script

on:
  workflow_dispatch:

jobs:
  job-summary-script:
    name: Write Summary from Action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await core.summary
              .addHeading('Test Results')
              .addTable([
                [{data: 'File', header: true}, {data: 'Result', header: true}],
                ['foo.js', 'Pass'],
                ['bar.js', 'Fail'],
                ['test.js', 'Pass']
              ])
              .addLink('View staging deployment!', 'https://github.com')
              .write()