name: Run Strategy

on:
  workflow_dispatch:

jobs:
  run-strategy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os_version: [ubuntu-22.04, ubuntu-20.04]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          echo "Node.js version: ${{ matrix.node-version }}"
          node --version
      - run: |
          echo "OS version: ${{ matrix.os_version }}"
          uname -a